#!/bin/sh

# Package
PACKAGE="gogs"
DNAME="Gogs"

INSTALL_DIR="/usr/local/${PACKAGE}"
SSS="/var/packages/${DNAME}/scripts/start-stop-status"
PATH="${INSTALL_DIR}:${PATH}"

SERVICETOOL="/usr/syno/bin/servicetool"
FWPORTS="/var/packages/${DNAME}/scripts/${PACKAGE}.sc"

FILE_CREATE_LOG="${INSTALL_DIR}/gogs/wizard_create_log"
LOG_FILE="/var/log/gogs.log"

SETTING_FILE="${INSTALL_DIR}/gogs/custom/conf/app.ini"

preinst ()
{
    if [[ -f "${SETTING_FILE}" ]]; then
        cp "${SETTING_FILE}" /tmp/gogs_app.ini
    fi
    exit 0
}

postinst ()
{
    # Link
    ln -s ${SYNOPKG_PKGDEST} ${INSTALL_DIR}

    # to create log at each start 
    if [ "${wizard_create_log}" == "true" ]; then
        touch ${FILE_CREATE_LOG}
    fi

    # Add firewall config
    ${SERVICETOOL} --install-configure-file --package ${FWPORTS} >> /dev/null

    if [[ -f "/tmp/gogs_app.ini" ]]; then
        mkdir -p "${INSTALL_DIR}/gogs/custom/conf"
        mv "/tmp/gogs_app.ini" ${SETTING_FILE}
    fi

    exit 0
}

preuninst ()
{
    # Stop the package
    ${SSS} stop > /dev/null

    # Remove firewall config
    if [ "${SYNOPKG_PKG_STATUS}" == "UNINSTALL" ]; then
        ${SERVICETOOL} --remove-configure-file --package ${PACKAGE}.sc >> /dev/null
    fi

    exit 0
}

postuninst ()
{
    # Remove link
    rm -f ${INSTALL_DIR}

    # remove log file
    rm -f ${LOG_FILE}

    exit 0
}

preupgrade ()
{
    # Stop the package
    ${SSS} stop > /dev/null

    if [[ -f "${SETTING_FILE}" ]]; then
        cp "${SETTING_FILE}" /tmp/gogs_app.ini
    fi

    exit 0
}

postupgrade ()
{
    if [[ -f "/tmp/gogs_app.ini" ]]; then
        mkdir -p "${INSTALL_DIR}/gogs/custom/conf"
        mv "/tmp/gogs_app.ini" ${SETTING_FILE}
    fi
    exit 0
}
